### PR TITLE
feat: adds commands page

### PR DESCRIPTION
**Pull request by devguilhermy**

### CODE REVIEW

**Review by ptrckbp — COMMENTED** [review]
As far as docs goes, this is good, but I don't know if we want our users to do this, as it looks like a second way of doing the same thing (which means more support / confusion, and it's trickier to remove this later). How does this differ from the reset the conversation button?

**Comment by LaurellaRobert** [comment]
Would it be helpful to nest this under e.g. the WhatsApp section, where the reset conversation button doesn't appear? (When testing a bot deployed via an integration, for instance)

**Review by ptrckbp — CHANGES_REQUESTED** [review]
@devguilhermy since this works for production bots too, i'd like to change this to "Bot commands" or "Special commands". Studio commands implies it only works in the studio. Also, I can see this being useful for some channels.

**Comment by rohankokkulabp** [comment]
yes, Bot Commands is good. I'd like to have it under shortcuts though

**Comment by rohankokkulabp** [comment]
Screenshot 2023-10-25 at 11 12 22 PM
like that

**Review by ptrckbp — APPROVED** [review]

**Review by ptrckbp — APPROVED** [review]

**Pull request merged**
